merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("band_list/", views.band_list, name="band-list"),
    path("bands/<int:id>/", views.band_detail, name="band-detail"),
    path("bands/add/", views.band_create, name="band-create"),
    path("bands/<int:id>/change", views.band_change, name="band-change"),
    path("bands/<int:id>/delete", views.band_delete, name="band-delete"),
    path("about-us", views.about, name="about"),
    path("listing-list", views.listing_list, name="listing-list"),
    path("listing/<int:id>/", views.listing_detail, name="listing-detail"),
    path("listing/add/", views.listing_create, name="listing-create"),
    path("listing/<int:id>/change", views.listing_change, name="listing-change"),
    path("listing/<int:id>/delete", views.listing_delete, name="listing-delete"),
    path("contact-us", views.contact, name="contact"),
    path("email-sent", views.email_sent, name="email-sent"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):
    def __str__(self):
        return f"{self.name}"

    name = models.fields.CharField(max_length=100)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    image = models.ImageField()

    class Genre(models.TextChoices):
        HIP_HOP = "HH"
        SYNTH_POP = "SP"
        ALTERNATIVE_ROCK = "AR"

    genre = models.fields.CharField(choices=Genre.choices, max_length=5)


class Listing(models.Model):
    def __str__(self):
        return f"{self.title}"

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=2000)
    year = models.fields.DateField(null=True)
    sold = models.fields.BooleanField(default=True)
    image = models.ImageField(upload_to="assets/img/")

    class Type(models.TextChoices):
        RECORDS = "RC"
        CLOTHING = "CT"
        POSTERS = "PS"
        MISCELLANEOUS = "MC"

    type = models.fields.CharField(choices=Type.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms
from listings.models import Listing, Band


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ("active", "official_homepage")


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = "__all__"


from . import models

# class PhotoForm(forms.ModelForm):
#     class Meta:
#         model = models.Photo
#         fields = ['image', 'caption']

merchex/listings/views.py
from typing import List
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band, Listing
from listings.forms import ContactUsForm
from django.core.mail import send_mail
from django.shortcuts import redirect

from listings.forms import BandForm, ListingForm


def band_list(request):
    bands = Band.objects.all()
    return render(
        request, "listings/band_list.html", {"bands": bands}
    )  # reponse, chemin pour accéder au template, dictionnaire de contexte


def band_detail(request, id):
    band = Band.objects.get(id=id)  # notez le paramètre id supplémentaire
    return render(
        request, "listings/band_detail.html", {"band": band}
    )  # nous passons l'id au modèle


def about(request):
    return render(request, "listings/about.html")


def listing_list(request):
    listings = Listing.objects.all()
    return render(request, "listings/listing_list.html", {"listings": listings})


def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request, "listings/listing_detail.html", {"listing": listing})


def contact(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data["message"],
                from_email=form.cleaned_data["email"],
                recipient_list=["admin@merchex.xyz"],
            )
        return redirect("email-sent")
    # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
    # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).
    else:
        form = ContactUsForm()
    return render(request, "listings/contact.html", {"form": form})


def email_sent(request):
    return render(request, "listings/email_sent.html")


def band_create(request):
    if request.method == "POST":
        form = BandForm(request.POST, request.FILES)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save(commit=False)
            print(band)
            band.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect("band-detail", band.id)

    else:
        form = BandForm()

    return render(request, "listings/band_create.html", {"form": form})


# @login_required
# def photo_upload(request):
#     form = forms.PhotoForm()
#     if request.method == 'POST':
#         form = forms.PhotoForm(request.POST, request.FILES)
#         if form.is_valid():
#             photo = form.save(commit=False)
#             # set the uploader to the user before saving the model
#             photo.uploader = request.user
#             # now we can save
#             photo.save()
#             return redirect('home')
#     return render(request, 'blog/photo_upload.html', context={'form': form})


def listing_create(request):
    if request.method == "POST":
        form = ListingForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            listing = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect("listing-detail", listing.id)

    else:
        form = ListingForm()

    return render(request, "listings/listing_create.html", {"form": form})


def band_change(request, id):
    band = Band.objects.get(id=id)

    if request.method == "POST":
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect("band-detail", band.id)
    else:
        form = BandForm(instance=band)

    return render(request, "listings/band_change.html", {"form": form})


def band_delete(request, id):
    band = Band.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == "POST":
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect("band-list")

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request, "listings/band_delete.html", {"band": band})


def listing_change(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == "POST":
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect("listing-detail", listing.id)
    else:
        form = ListingForm(instance=listing)

    return render(request, "listings/listing_change.html", {"form": form})


def listing_delete(request, id):
    listing = Listing.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == "POST":
        # supprimer le groupe de la base de données
        listing.delete()
        # rediriger vers la liste des groupes
        return redirect("listing-list")

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request, "listings/listing_delete.html", {"listing": listing})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
<p>"about works!"</p>

{% endblock %}

merchex/listings/templates/listings/band_change.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Mise à jour du groupe</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>


{% endblock %}

merchex/listings/templates/listings/band_create.html
# listings/templates/listings/band_create.html

{% extends 'listings/base.html' %}

{% block content %}

 <h1>Créer un nouveau groupe</h1>

  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active|yesno }}</li>
   {% if band.official_homepage %}
   <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
    {% endif %}
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-change' band.id %}">Modifier</a>
<a href="{% url 'band-delete' band.id %}">Supprimer</a>

<p>Annonces de {{ band.name }}</p>
<ul>{% for listing in band.listing_set.all %}
    <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
    {% endfor %}
</ul>
<br>
<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}
{% load static %} 
{% block content %}


<!-- <h1>Groupes</h1> -->
<link rel="stylesheet" href="{% static 'css/list-page.css' %}"/>

<section class="page-section portfolio" id="portfolio">

    <div class="container">
        <!-- Portfolio Section Heading-->
        <div class="text-center">
            <h2 class="page-section-heading text-secondary mb-0 d-inline-block">Groupes</h2>
        </div>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
    </div>
</section>

<div>
    <button><a href="{% url 'band-create' %}" class="write-new-button">Créer un nouveau groupe</a></button>
    </p>
    <div class="groups">
        {% for band in bands %}
            <div class="group">
                <h3 class="u-custom-font u-font-pt-sans u-text u-text-grey-50 u-text-3"><a href="{% url 'band-detail' band.id %}">{{band.name}}</a></h3>
                <img class="img-group" src="{% band.image.url %}" alt="image du groupe de musique">
                <a href="{% url 'band-detail' band.id %}">Détails</a> - <a href="{% url 'band-change' band.id %}">Editer</a>           
            </div>
        {%endfor%}
    </div>
    </div>
    <button><a href="{% url 'band-create' %}" class="write-new-button">Créer un nouveau groupe</a></button>
               
    




<!-- <a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
<p>Mes groupes préférés sont : 
</p>
<ul>
    {%for band in bands%}
    <li class="groupe-icon"><a href="{% url 'band-detail' band.id %}">{{band.name}}</a>
        - <a href="{% url 'band-change' band.id %}">[Editer]</a></li>
    
    {%endfor%}
</ul> -->

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Freelancer - Start Bootstrap Theme</title>
        <!-- Font Awesome icons (free version)-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
        <!-- Core theme CSS (includes Bootstrap)-->
        <!-- <link href="css/styles.css" rel="stylesheet"> -->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}"/> 
        <!-- Fonts CSS-->
        <link rel="stylesheet" href="{% static 'css/heading.css' %}">
        <link rel="stylesheet" href="{% static 'css/body.css' %}">
    </head>
    <body id="page-top">
        <nav class="navbar navbar-expand-lg bg-secondary fixed-top" id="mainNav">
            <img id="logo" class="navbar-brand js-scroll-trigger"  src="{% static 'assets/img/monkey_logo.png' %}" alt="logo singe"><img>
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">MusicMania</a>
                <button class="navbar-toggler navbar-toggler-right font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu <i class="fas fa-bars"></i></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'band-list' %}">Groupes</a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'listing-list' %}">Annonces</a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'contact' %}">Contact</a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'about' %}">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image<img class="masthead-avatar mb-5" src="assets/img/avataaars.svg" alt=""> -->
                <!-- Masthead Heading-->
                <h1 class="masthead-heading mb-0">MM</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="pre-wrap masthead-subheading font-weight-light mb-0"> Temple des fans - Vente d'objets collector</p>
                <img id="image-index" src="{% static 'assets/img/monkey_welcome.png' %}" alt="image groupe de musique"><img>
            </div>
        </header>
        {% block content %}{% endblock %}
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="mb-4">LOCATION</h4>
                        <p class="pre-wrap lead mb-0">23 rue de la Ruche, Lyon</p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="mb-4">AROUND THE WEB</h4><a class="btn btn-outline-light btn-social mx-1" href="https://www.facebook.com/StartBootstrap"><i class="fab fa-fw fa-facebook-f"></i></a><a class="btn btn-outline-light btn-social mx-1" href="https://www.twitter.com/sbootstrap"><i class="fab fa-fw fa-twitter"></i></a><a class="btn btn-outline-light btn-social mx-1" href="https://www.linkedin.com/in/startbootstrap"><i class="fab fa-fw fa-linkedin-in"></i></a><a class="btn btn-outline-light btn-social mx-1" href="https://www.dribble.com/startbootstrap"><i class="fab fa-fw fa-dribbble"></i></a>
                    </div>
                    <!-- Footer About Text -->
                    <div class="col-lg-4">
                        <h4 class="mb-4">ABOUT MusicMania</h4>
                        <p class="pre-wrap lead mb-0">MusicMania is a free to use, MIT licensed Bootstrap theme created by Start Bootstrap</p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <!-- <section class="copyright py-4 text-center text-white">
            <div class="container"><small class="pre-wrap">Copyright © Your Website 2020</small></div>
        </section> -->
        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->
        <div class="scroll-to-top d-lg-none position-fixed"><a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top"><i class="fa fa-chevron-up"></i></a></div>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
        <script src="{% static 'assets/mail/jqBootstrapValidation.js'%}"></script>
        <script src="{% static 'assets/mail/contact_me'%}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js'%}"></script>
    </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Contactez nous !</h1>
<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Soumettre">
</form>
…

{% endblock %}

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Merci ! Votre message a bien été envoyé !</h1>
{% endblock %}

merchex/listings/templates/listings/listing_change.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Mise à jour de l'annonce</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>

 {% endblock %}

merchex/listings/templates/listings/listing_create.html
# listings/templates/listings/band_create.html

{% extends 'listings/base.html' %}

{% block content %}

 <h1>Ecrire une nouvelle annonce</h1>

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_delete.html
<h1>Supprimer l'annonce</h1>

<p>Etes-vous sûr de vouloir supprimer l'annonce : {{ listing.title }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ listing.title }}</h2>

<ul>
 <li>Type : {{ listing.get_type_display }}</li>
 <li>Année de parution : {{ listing.year }}</li>
 {% if listing.band %}
    <li>Groupe : <a href="{% url 'band-detail' listing.band.id %}">{{ listing.band }}</a></li>
 {% endif %}
 <li>Vendu : {{ listing.sold|yesno }}</li>
</ul>

<p>{{ listing.description }}</p>

<a href="{% url 'listing-change' listing.id %}">Modifier</a>
<a href="{% url 'listing-delete' listing.id %}">Supprimer</a>

<a href="{% url 'listing-list' %}">Retour à tous la liste des annonces</a>

{% endblock %}

<!-- title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=2000)
    year = models.fields.DateField(null=True)
    sold = models.fields.BooleanField(default=True) -->

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}
{% load static %} 
{% block content %}
<!-- <h1>Annonces quotidiennes</h1> -->
<link rel="stylesheet" href="{% static 'css/list-page.css' %}"/>

<section class="page-section portfolio" id="portfolio">
    <div class="container">
        <!-- Portfolio Section Heading-->
        <div class="text-center">
            <h2 class="page-section-heading text-secondary mb-0 d-inline-block">Annonces</h2>
        </div>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
    </div>
</section>
<button><a href="{% url 'listing-create' %}" class="write-new-button">Nouvelle annonce</a></button>
    <div class="listings"> 
        {%for listing in listings%}
        <div class="listing">
            <h3 id="listing-title" class="u-custom-font u-font-pt-sans u-text u-text-grey-50 u-text-3"><a href="{% url 'listing-detail' listing.id %}">{{listing.title}}</a></h3>
            <img class="img-listing" src="{% static listing.image %}" alt="image de l'objet">
            <div>{{listing.image}}</div>
            <span><a href="{% url 'listing-detail' listing.id %}">Détails</a> - <a href="{% url 'listing-change' listing.id %}">Editer</a></span> 
        </div>    
        {%endfor%}
    </div>
<button class="button"><a href="{% url 'listing-create' %}" class="write-new-button">Nouvelle annonce</a></button>
{% endblock %}
<!-- 
    <div>
    <a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
    </p>
    <div class="groups">
        {%for band in bands%}
            <div class="group">
                <h3 class="u-custom-font u-font-pt-sans u-text u-text-grey-50 u-text-3"><a href="{% url 'band-detail' band.id %}">{{band.name}}</a></h3>
                <img class="img-group" src="{% static band.image %}" alt="image du groupe de musique">
                <div>{{band.image}}</div>
                <span><a href="{% url 'band-detail' band.id %}">Détails</a> - <a href="{% url 'band-change' band.id %}">Editer</a></span>           
            </div>
        {%endfor%}
    </div>
    </div>
    <a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

<div>
    <a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
    </p>
    <div class="groups">
        {%for band in bands%}
<div class="group">
    <h3 class="u-custom-font u-font-pt-sans u-text u-text-grey-50 u-text-3"><a href="{% url 'band-detail' band.id %}">{{band.name}}</a></h3>
    <img class="img-group" src="{% static band.image %}" alt="image du groupe de musique">
    <span><a href="{% url 'band-detail' band.id %}">Détails</a> - <a href="{% url 'band-change' band.id %}">Editer</a></span>           
</div>
{%endfor%} -->